apiVersion: v1
kind: Namespace
metadata:
  name: clusters-lab
---
apiVersion: v1
data:
 .dockerconfigjson: CHANGEME
kind: Secret
metadata:
  name: lab-pull-secret
  namespace: clusters-lab
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: lab-ssh-key
  namespace: clusters-lab
stringData:
  id_rsa.pub: CHANGEME
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: capi-provider-role
  namespace: clusters-lab
rules:
- apiGroups:
  - agent-install.openshift.io
  resources:
  - agents
  verbs:
  - '*'
---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: lab
  namespace: clusters-lab
spec:
  pullSecretRef:
    name: lab-pull-secret
  sshAuthorizedKey: CHANGEME
  agentLabels:
    cluster-name: clusters-lab
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: clusters-lab
---
