apiVersion: v1
data:
 .dockerconfigjson: CHANGEME
kind: Secret
metadata:
  name: lab-pull-secret
  namespace: clusters
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: lab-ssh-key
  namespace: clusters
stringData:
  id_rsa.pub: CHANGEME
---
apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: lab
  namespace: clusters
spec:
  release:
    image: "quay.io/openshift-release-dev/ocp-release@sha256:b9d6ccb5ba5a878141e468e56fa62912ad7c04864acfec0c0056d2b41e3259cc"
  dns:
    baseDomain: 192-168-122-248.sslip.io
  etcd:
    managed:
      storage:
        persistentVolume:
          size: 4Gi
        restoreSnapshotURL: null
        type: PersistentVolume
    managementType: Managed
  pullSecret:
    name: lab-pull-secret
  sshKey:
    name: lab-ssh-key
  fips: False
  networking:
    clusterNetwork:
    - cidr: 10.129.0.0/14
      hostPrefix: 23
    serviceNetwork:
    - cidr: 172.31.0.0/16
    machineNetwork:
    - cidr: 192.168.122.0/24
    networkType: OVNKubernetes
  platform:
    agent:
      agentNamespace: clusters-lab
    type: Agent
  infraID: lab
  dns:
    baseDomain: 192-168-122-248.sslip.io
  services:
  - service: APIServer
    servicePublishingStrategy:
      nodePort:
        address: 10.19.135.112
      type: NodePort
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: OIDC
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route
  - service: OVNSbDb
    servicePublishingStrategy:
      type: Route
---
